### PR TITLE
Implement of using unified image

### PR DESCRIPTION
**Pull request by sw37th**
Hi,

This is an implement of LXD VMM driver using unified image format instead of raw unix-brock image.
This driver uses LXD REST API (or lxc cli) to import/export image and it does not need require root privilege. I think that this would reduce requirements for installation.

The config of container's security.privilege and security.nested are optional. It can define at Template:
```
LXD_CONFIG=[
  SECURITY_NESTING="true",
  SECURITY_PRIVILEGED="true" ]
```
If Node's /var/lib/lxd is created by Btrfs, it can use disk quota:
```
DISK=[
  IMAGE_ID="6",
  LXD_QUOTA_SIZE="20480" ]   # 20GB
```
The container does not have CONTEXT iso disk. context.sh is injected via REST API from host directly.

### CODE REVIEW

**Comment by jmdelafe** [comment]
@sw37th, can you please make a pull request in wich the changes you have made are applied to the files in "remotes" folder? We think is better than having two sets of scripts.

**Comment by sw37th** [comment]
OK, I have moved scripts into "remotes".

**Comment by jmdelafe** [comment]
@sw37th, as you can see, we are working with the stuff you created. There are two new branches **sw37th-checkout** and **sw37th-use_unified_image**. We love the way you put context files inside the container and we checked that there are great performance improvements included in your code. This changes are almost added to our code :)

The new way to mess with the OpenNebula's images and lxc image repository it's really great because it leaves "the sticky work" to the LXD API. But we noticed that we lose some functionalities and performance:
- if we choose to use that way we can't attach "extra" disk to the container in the way that OpenNebula do (ex: attaching a disk as _/dev/sda_ device)
- also, if we use a distributed storage software (like _Ceph_) and the _node_ where the container is running dramatically fails (or the disk where the LXD images are), the changes made in the container since the last boot, will be lost.

Besides we wanna thanks you for the VNC issue solved. Excellent work! That issue was a pain in the $@#^& for a long time :)

**Comment by sw37th** [comment]
@jmdelafe, thank you.

> * if we choose to use that way we can't attach "extra" disk to the container in the way that OpenNebula do (ex: attaching a disk as /dev/sda device)

Maybe implement feature of attach extra disk without large design change is not so difficult.
I will try it.

> * also, if we use a distributed storage software (like Ceph) and the node where the container is running dramatically fails (or the disk where the LXD images are), the changes made in the container since the last boot, will be lost.

I understand. This way Node uses two image store, OpenNebula's datastore (/var/lib/one) and LXD's image store (/var/lib/lxd). And usually LXD's image store allocated on Node's local storage.
How about create LXD's image store on distributed storage, and symbolic linked to /var/lib/lxd on each Nodes?

**Comment by dann1** [comment]
Hello @sw37th, we're doing a lot of changes with most of your contributions and other stuff to release version 1707. 
I like the idea of using native lxd storage, although you couldn't limit storage size if you use dist backend but, the most useful case for this would be OpenNebula tm driver. This way ***lxc image import path-to-tar.gz*** would be like uploading the base image to OpenNebula and creating container during lxc launch would be prolog in OpenNebula. This might work but still requires some thoughts about implementation.

**Comment by sw37th** [comment]
Hello @dann1, congratulations on version 1707 release!

> This way lxc image import path-to-tar.gz would be like uploading the base image to OpenNebula and creating container during lxc launch would be prolog in OpenNebula. This might work but still requires some thoughts about implementation.

I agree. It seems to be best way.

**Comment by dann1** [comment]
@sw37th why do you disable cloud-init. I'm not sure if installing cloud init is really necessary, I just install it because OpenNebula says so. I've been told we don't need it but if you could tell me a bit about what it is used for in OpenNebula context it would be nice.

**Comment by sw37th** [comment]
Hello @dann1.
The work of initial boot time of Cloud-init overlaps with OpenNebula one-context, such as network configuration, copy SSH authorized_keys.
If virtual machine or container using OpenNebula one-context, Cloud-init is not necessary.
Cloud-init can work multi cloud environment. It doesn't support some OpenNebula's function (disk resize, device attach, etc...) but can expect that the VM/container image run on another cloud environment.

On Cloud-init's datasource implementation for OpenNebula, Cloud-init uses CONTEXT iso as block device. I changed to omit CONTEXT iso and push context.sh to container directly, so Cloud-init doesn't work well now.
If you want to use Cloud-init, please delete my code, and revert to use CONTEXT iso.

**Comment by dann1** [comment]
I like the file injection way more than the default iso approach, just didn't know what cloud-init was for because you disabled the services in the guide. Thanks for the info.

**Comment by dann1** [comment]
Im opening a feature issue read https://github.com/OpenNebula/addon-lxdone/issues/17

**Pull request closed without merging**
